remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Thiyaneshwaran 
  tagline: Hacker | Bug Hunter | Infosec Noob
  date_format: "%b %-d, %Y"

  social_links:
    twitter: th4nu_0x0
    github: th4nu-0x0
    linkedIn:  # format: locale/username
    
  plainwhite:
    portfolio_image:  "assets/hacker.svg"
  
  plainwhite:
    navigation:
      - title: Posts
        url: "/posts"
      - title: About Me
        url: "/about"

show_excerpts: true
