remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Thiyaneshwaran 
  tagline: Hacker | Infosec Noob
  date_format: "%b %-d, %Y"

  social_links:
    twitter: th4nu_0x0
    github: th4nu-0x0
    linkedIn:  # format: locale/username
    
  portfolio_image:  "assets/hacker.svg"

  navigation:
    - title: Posts
      url: "/posts"
    - title: About Me
      url: "/about"
        
  dark_mode: true
  
  condensed_mobile:
    - home
    - post
    - page
  
  search: true
  
  html_lang: "en"

  plugins:
    - jekyll-seo-tag
